-- IOIS PLATFORM — Supabase schema
create extension if not exists pgcrypto;
do $$ begin create type public.member_status as enum ('pending','active','suspended','rejected'); exception when duplicate_object then null; end $$;
do $$ begin create type public.payment_status as enum ('PENDING','APPROVED','REJECTED'); exception when duplicate_object then null; end $$;
create table if not exists public.membership_plans (id uuid primary key default gen_random_uuid(),plan_code text unique not null,plan_name text not null,display_name text,amount numeric(12,2) not null check(amount>=0),payout numeric(12,2) default 0,description text,features jsonb not null default '[]'::jsonb,is_active boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade,full_name text,mobile text,email text,account_status text not null default 'active',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.members (id uuid primary key default gen_random_uuid(),auth_user_id uuid unique not null references auth.users(id) on delete cascade,member_id text unique,plan_id text,plan_amount numeric(12,2) not null default 0,membership_status public.member_status not null default 'pending',referral_code text,referred_by text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),selected_services jsonb not null default '[]'::jsonb);
create table if not exists public.payments (id uuid primary key default gen_random_uuid(),member_id uuid not null references public.members(id) on delete cascade,payment_method text not null default 'UPI',upi_id text,transaction_reference text,payment_status public.payment_status not null default 'PENDING',amount numeric(12,2),admin_note text,created_at timestamptz not null default now(),verified_at timestamptz);
create table if not exists public.referrals (id uuid primary key default gen_random_uuid(),referrer_member_id uuid references public.members(id) on delete set null,referred_member_id uuid references public.members(id) on delete cascade,referral_code text,payout_amount numeric(12,2) default 0,status text not null default 'pending',created_at timestamptz not null default now());
create table if not exists public.admin_profiles (user_id uuid primary key references auth.users(id) on delete cascade,role text not null default 'admin',created_at timestamptz not null default now());
insert into public.membership_plans(plan_code,plan_name,display_name,amount,payout,features) values
('starter','Starter','Alpha Starter Pass',10,7,'["Digital ID Pass","3 CV Templates","2 Cover Letters","10 ChatGPT Prompts","Useful Website Links"]'),('basic','Basic','Nexus Pro Creator Kit',49,35,'["Pro Creator Badge","15+ Bio-data","50+ Social Posts","Smartphone Website Guide"]'),('plus','Plus','Apex Executive Pass',99,70,'["Executive Business Pass","100+ Branding Templates","Logos","Business Card Bundle"]'),('premium','Premium','Zenith VIP Creator',199,120,'["VIP Creator Card","Mobile Design Masterclass","300+ Marketing Banners"]'),('pro','Pro','Govt Exam & Student',299,220,'["Student ID Card","Govt Job Alert Sheet","GK & Exam Notes"]'),('business','Business','Diamond Business Agency',499,375,'["Diamond Agency Card","1000+ Graphic Assets","Video Assets","Agency Manual"]'),('enterprise','Enterprise','VIP Mastermind & AI',999,750,'["VIP Elite Card","ChatGPT / Canva AI Mastery","Freelancing Blueprint"]') on conflict(plan_code) do update set plan_name=excluded.plan_name,display_name=excluded.display_name,amount=excluded.amount,payout=excluded.payout,features=excluded.features,is_active=true;
alter table public.members add column if not exists selected_services jsonb not null default '[]'::jsonb;

create or replace function public.make_member_id() returns text language plpgsql as $$ declare v text; begin loop v:='IOIS-'||to_char(current_date,'YYYY')||'-'||upper(substr(encode(gen_random_bytes(5),'hex'),1,10)); exit when not exists(select 1 from public.members where member_id=v); end loop; return v; end $$;
create or replace function public.handle_new_iois_user() returns trigger language plpgsql security definer set search_path=public as $$ declare plan text; amount numeric; begin plan:=coalesce(new.raw_user_meta_data->>'plan_id','starter'); select mp.amount into amount from public.membership_plans mp where mp.plan_code=plan and mp.is_active=true limit 1; amount:=coalesce(amount,10); insert into public.profiles(id,full_name,mobile,email) values(new.id,new.raw_user_meta_data->>'full_name',new.raw_user_meta_data->>'mobile',new.email) on conflict(id) do update set full_name=excluded.full_name,mobile=excluded.mobile,email=excluded.email,updated_at=now(); insert into public.members(auth_user_id,member_id,plan_id,plan_amount,referral_code,referred_by,selected_services) values(new.id,public.make_member_id(),plan,amount,nullif(new.raw_user_meta_data->>'referral_code',''),nullif(new.raw_user_meta_data->>'referred_by',''),coalesce(new.raw_user_meta_data->'selected_services','[]'::jsonb)) on conflict(auth_user_id) do nothing; return new; end $$;
drop trigger if exists on_auth_user_created_iois on auth.users;
create trigger on_auth_user_created_iois after insert on auth.users for each row execute function public.handle_new_iois_user();
alter table public.membership_plans enable row level security; alter table public.profiles enable row level security; alter table public.members enable row level security; alter table public.payments enable row level security; alter table public.referrals enable row level security; alter table public.admin_profiles enable row level security;

drop policy if exists "plans public read" on public.membership_plans;
drop policy if exists "profile own read" on public.profiles;
drop policy if exists "profile own insert" on public.profiles;
drop policy if exists "profile own update" on public.profiles;
drop policy if exists "member own read" on public.members;
drop policy if exists "member own insert" on public.members;
drop policy if exists "payment own read" on public.payments;
drop policy if exists "payment own insert" on public.payments;
drop policy if exists "referral own read" on public.referrals;
drop policy if exists "admin plans manage" on public.membership_plans;
drop policy if exists "admin profiles read" on public.profiles;
drop policy if exists "admin members all" on public.members;
drop policy if exists "admin payments all" on public.payments;
drop policy if exists "admin referrals all" on public.referrals;
drop policy if exists "admin profile self" on public.admin_profiles;
create policy "plans public read" on public.membership_plans for select using(is_active=true);
create policy "profile own read" on public.profiles for select using(auth.uid()=id); create policy "profile own insert" on public.profiles for insert with check(auth.uid()=id); create policy "profile own update" on public.profiles for update using(auth.uid()=id);
create policy "member own read" on public.members for select using(auth.uid()=auth_user_id); create policy "member own insert" on public.members for insert with check(auth.uid()=auth_user_id);
create policy "payment own read" on public.payments for select using(exists(select 1 from public.members m where m.id=member_id and m.auth_user_id=auth.uid())); create policy "payment own insert" on public.payments for insert with check(exists(select 1 from public.members m where m.id=member_id and m.auth_user_id=auth.uid()));
create policy "referral own read" on public.referrals for select using(exists(select 1 from public.members m where m.id=referrer_member_id and m.auth_user_id=auth.uid()) or exists(select 1 from public.members m where m.id=referred_member_id and m.auth_user_id=auth.uid()));
-- After creating the admin account: insert into public.admin_profiles(user_id,role) values('YOUR-AUTH-USER-UUID','admin');
create policy "admin plans manage" on public.membership_plans for all using(exists(select 1 from public.admin_profiles a where a.user_id=auth.uid())) with check(exists(select 1 from public.admin_profiles a where a.user_id=auth.uid()));
create policy "admin profiles read" on public.profiles for select using(exists(select 1 from public.admin_profiles a where a.user_id=auth.uid())); create policy "admin members all" on public.members for all using(exists(select 1 from public.admin_profiles a where a.user_id=auth.uid())) with check(exists(select 1 from public.admin_profiles a where a.user_id=auth.uid())); create policy "admin payments all" on public.payments for all using(exists(select 1 from public.admin_profiles a where a.user_id=auth.uid())) with check(exists(select 1 from public.admin_profiles a where a.user_id=auth.uid())); create policy "admin referrals all" on public.referrals for all using(exists(select 1 from public.admin_profiles a where a.user_id=auth.uid())) with check(exists(select 1 from public.admin_profiles a where a.user_id=auth.uid())); create policy "admin profile self" on public.admin_profiles for select using(user_id=auth.uid());
